# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-27 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='name',
        ),
    ]
